<?php

namespace ContainerGi9YxqU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1fdu00EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1fdu00E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1fdu00E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'adresserepo' => ['privates', 'App\\Repository\\AdresseRepository', 'getAdresseRepositoryService', true],
            'rolerepo' => ['privates', 'App\\Repository\\RoleRepository', 'getRoleRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.1fdu00E.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.1fdu00E": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'Manager' => '?',
            'adresserepo' => 'App\\Repository\\AdresseRepository',
            'rolerepo' => 'App\\Repository\\RoleRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
