<?php

namespace ContainerGi9YxqU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MKEdqcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MKEdqc_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MKEdqc_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CompagnieController::delete' => ['privates', '.service_locator..W5wjef', 'get_ServiceLocator__W5wjefService', true],
            'App\\Controller\\CompagnieController::store' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CompagnieController::update' => ['privates', '.service_locator._JdKj9p', 'get_ServiceLocator_JdKj9pService', true],
            'App\\Controller\\RegistrationController::index' => ['privates', '.service_locator.dTaHD7m', 'get_ServiceLocator_DTaHD7mService', true],
            'App\\Controller\\TacheController::delete' => ['privates', '.service_locator.GJi4qMg', 'get_ServiceLocator_GJi4qMgService', true],
            'App\\Controller\\TacheController::index' => ['privates', '.service_locator.S9zgqlS', 'get_ServiceLocator_S9zgqlSService', true],
            'App\\Controller\\TacheController::upgate' => ['privates', '.service_locator.GJi4qMg', 'get_ServiceLocator_GJi4qMgService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.xZ4BuEO', 'get_ServiceLocator_XZ4BuEOService', true],
            'App\\Controller\\UserController::store' => ['privates', '.service_locator.PTsd.1b', 'get_ServiceLocator_PTsd_1bService', true],
            'App\\Controller\\UserController::update' => ['privates', '.service_locator.1fdu00E', 'get_ServiceLocator_1fdu00EService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CompagnieController:delete' => ['privates', '.service_locator..W5wjef', 'get_ServiceLocator__W5wjefService', true],
            'App\\Controller\\CompagnieController:store' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CompagnieController:update' => ['privates', '.service_locator._JdKj9p', 'get_ServiceLocator_JdKj9pService', true],
            'App\\Controller\\RegistrationController:index' => ['privates', '.service_locator.dTaHD7m', 'get_ServiceLocator_DTaHD7mService', true],
            'App\\Controller\\TacheController:delete' => ['privates', '.service_locator.GJi4qMg', 'get_ServiceLocator_GJi4qMgService', true],
            'App\\Controller\\TacheController:index' => ['privates', '.service_locator.S9zgqlS', 'get_ServiceLocator_S9zgqlSService', true],
            'App\\Controller\\TacheController:upgate' => ['privates', '.service_locator.GJi4qMg', 'get_ServiceLocator_GJi4qMgService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.xZ4BuEO', 'get_ServiceLocator_XZ4BuEOService', true],
            'App\\Controller\\UserController:store' => ['privates', '.service_locator.PTsd.1b', 'get_ServiceLocator_PTsd_1bService', true],
            'App\\Controller\\UserController:update' => ['privates', '.service_locator.1fdu00E', 'get_ServiceLocator_1fdu00EService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CompagnieController::delete' => '?',
            'App\\Controller\\CompagnieController::store' => '?',
            'App\\Controller\\CompagnieController::update' => '?',
            'App\\Controller\\RegistrationController::index' => '?',
            'App\\Controller\\TacheController::delete' => '?',
            'App\\Controller\\TacheController::index' => '?',
            'App\\Controller\\TacheController::upgate' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::store' => '?',
            'App\\Controller\\UserController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CompagnieController:delete' => '?',
            'App\\Controller\\CompagnieController:store' => '?',
            'App\\Controller\\CompagnieController:update' => '?',
            'App\\Controller\\RegistrationController:index' => '?',
            'App\\Controller\\TacheController:delete' => '?',
            'App\\Controller\\TacheController:index' => '?',
            'App\\Controller\\TacheController:upgate' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:store' => '?',
            'App\\Controller\\UserController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
