<?php

namespace ContainerErzfcMa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6YSh_ELService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6YSh.EL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6YSh.EL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compagnie' => ['privates', '.errored..service_locator.6YSh.EL.App\\Entity\\Compagnie', NULL, 'Cannot autowire service ".service_locator.6YSh.EL": it needs an instance of "App\\Entity\\Compagnie" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'compagnie' => 'App\\Entity\\Compagnie',
            'em' => '?',
        ]);
    }
}
