<?php

namespace ContainerD7KqFvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JdKj9pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._JdKj9p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._JdKj9p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adresseRepo' => ['privates', 'App\\Repository\\AdresseRepository', 'getAdresseRepositoryService', true],
            'compagnie' => ['privates', '.errored..service_locator._JdKj9p.App\\Entity\\Compagnie', NULL, 'Cannot autowire service ".service_locator._JdKj9p": it needs an instance of "App\\Entity\\Compagnie" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'adresseRepo' => 'App\\Repository\\AdresseRepository',
            'compagnie' => 'App\\Entity\\Compagnie',
            'em' => '?',
        ]);
    }
}
