<?php

namespace ContainerD7KqFvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TacheController' shared autowired service.
     *
     * @return \App\Controller\TacheController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TacheController.php';

        $container->services['App\\Controller\\TacheController'] = $instance = new \App\Controller\TacheController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\CompagnieRepository'] ?? $container->load('getCompagnieRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\TacheController', $container));

        return $instance;
    }
}
