<?php

namespace Container6lO8CmN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5PkTFPoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5PkTFPo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5PkTFPo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compagnieRep' => ['privates', 'App\\Repository\\CompagnieRepository', 'getCompagnieRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'compagnieRep' => 'App\\Repository\\CompagnieRepository',
            'em' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
