<?php

namespace Container6lO8CmN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompagnieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6YSh.EL.App\Entity\Compagnie' shared service.
     *
     * @return \App\Entity\Compagnie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6YSh.EL": it needs an instance of "App\\Entity\\Compagnie" but this type has been excluded in "config/services.yaml".');
    }
}
