<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGi9YxqU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGi9YxqU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGi9YxqU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGi9YxqU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGi9YxqU\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gi9YxqU',
    'container.build_id' => 'da7c30f8',
    'container.build_time' => 1696769244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGi9YxqU');
