<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6lO8CmN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6lO8CmN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6lO8CmN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6lO8CmN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6lO8CmN\App_KernelDevDebugContainer([
    'container.build_hash' => '6lO8CmN',
    'container.build_id' => '6df7b336',
    'container.build_time' => 1696729680,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6lO8CmN');
